name: Automatic pull request review

on: [pull_request]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        if: github.actor == 'AndrewMusgrave'
        uses: andrewmusgrave/automatic-pull-request-review@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          event: APPROVE
